"""changed columns migration

Revision ID: 8e304b7735fb
Revises: 9be918db7c45
Create Date: 2026-02-21 15:39:41.646419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e304b7735fb'
down_revision: Union[str, Sequence[str], None] = '9be918db7c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_events', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_events', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True)
    # ### end Alembic commands ###
