"""Inital migration

Revision ID: 9be918db7c45
Revises: 
Create Date: 2026-02-21 12:10:35.014964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be918db7c45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_events',
    sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.String(length=20), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('merchant_tier', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_merchant_events_merchant_id'), 'merchant_events', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_events_merchant_id'), table_name='merchant_events')
    op.drop_table('merchant_events')
    # ### end Alembic commands ###
